### ISSUE TITLE
'css-animation' does not contain an export named 'isCssAnimationSupported'.

### ISSUE THREAD

**Issue by VanDavv** [yiminghe/css-animation#14]
Hi!
I've been using `rc-slider` package, and I got following error 

> ./node_modules/rc-animate/es/AnimateChild.js
> 76:11-34 'css-animation' does not contain an export named 'isCssAnimationSupported'.

As listed in `npm list` command, it uses internally Your package

> ├─┬ rc-slider@8.3.1
> │ ├── classnames@2.2.5
> │ ├─┬ rc-tooltip@3.4.8
> │ │   └─┬ rc-trigger@1.11.3
> │ │        ├─┬ rc-align@2.3.4
> │ │             └── dom-align@1.6.3
> │ │        └─┬ rc-animate@2.4.1
> │ │              └─┬ css-animation@1.4.0
> │ │                    └─┬ component-classes@1.2.6
> │ │                          └── component-indexof@0.0.3

Code worked on version `1.3.2` and stopped working on version `1.4.0`

In `rc-animate` package, import from `css-animation` looks like this:

`import cssAnimate, { isCssAnimationSupported } from 'css-animation';`

Did something change in the API?

**Comment by therewillbecode** [comment]
The examples for version 1.4 of css-animation show that the API has changed to:

`import anim from 'css-animation';`

**Comment by VanDavv** [comment]
But, regarding semantic versioning, this change should affect major part, not minor.
This means, it shouldn't change from `1.3.2` to `1.4.0`, but from `1.3.2` to `2.0.0`
