### ISSUE TITLE
如何让服务器端和浏览器端渲染的结果一致？

### ISSUE THREAD

**Issue by snadn** [yiminghe/css-animation#3]
isCssAnimationSupported 的判断在服务器端总是 false，但在浏览器端可能是 true。

从而导致两端渲染的结果不一致。

![image](https://cloud.githubusercontent.com/assets/1269858/14040707/e45fb8ca-f2a4-11e5-9033-e88a3dcc67e4.png)

有没有方法让其一致，不产生warning呢？

**Comment by yiminghe** [comment]
到 ant-design 提 issue
