### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by prisonier** [yiminghe/css-animation#4]
Hi,

One of the module on my app uses your module but I get the `document is not defined `error when webpack build my app.

The issue comes from [here](https://github.com/yiminghe/css-animation/blob/master/src/Event.js#L22)

I simply added a `typeof document !== 'undefined' `check on document but I don't know if there is any side effects ? 

[PR just here if there is no side effects](https://github.com/yiminghe/css-animation/pull/5)

[This issue on the module which depends on yours](https://github.com/lynndylanhurley/redux-auth/issues/41)

**Comment by yiminghe** [comment]
1.2.3

**Comment by prisonier** [comment]
Thanks for have been doing this so quick.
